STIKER_001 = [
    "CAACAgUAAxkBAAEHRg1jxSZx9fYwCj3zXy-IgF_XFUDANgACEAEAAurMEVWu4_78o_0ELC0E",
    "CAACAgUAAxkBAAEHRiBjxSbA_ovxZcKK3uGADmW9E7lPdQACGQIAAgtSAAFVo5g_wIaPweUtBA",
    "CAACAgUAAxkBAAEHRjVjxSbjF1Fwv2gBWlPRllbA0-r4hAAC9gADenrYVOJbhj_diRf7LQQ",
    "CAACAgUAAxkBAAEHRlJjxScGdpB2-fOfnmEnYDd9yOw65AACVgEAAgLMaVXLTsryCB2bTi0E",
    "CAACAgUAAxkBAAEHRmNjxScT9NXMgJCvFqJ2K7B5FXXwWAACcAEAAok2IVXK3CfHdJckzi0E",
    "CAACAgUAAxkBAAEHRm9jxSch7pucB-QBniJGKjheOtaBggACSQEAAhn2GFV34BbE07DUMC0E",
    "CAACAgUAAxkBAAEHRn1jxScywvQU1YZtVcqhNJOxtKhX5QACdQEAApsDEVUsAklEg-h7sS0E",
    "CAACAgUAAxkBAAEHRotjxSdB4lvcN370CmF9s746Z2jKnwACdAEAAoNuEFV0MDfYsbWlpC0E",
    "CAACAgUAAxkBAAEHRpNjxSdNqaVakddYssD6Y8d60EIbhwACqQEAAhN3-FTtyp61blwoMS0E",
]